// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// is_rust_compiled_cpp
bool is_rust_compiled_cpp();
RcppExport SEXP _gps2gtfs_is_rust_compiled_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(is_rust_compiled_cpp());
    return rcpp_result_gen;
END_RCPP
}
// haversine_distance_cpp
double haversine_distance_cpp(double lat1, double lon1, double lat2, double lon2);
RcppExport SEXP _gps2gtfs_haversine_distance_cpp(SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_distance_cpp(lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// match_points_to_buffers_cpp
CharacterVector match_points_to_buffers_cpp(NumericVector gps_lat, NumericVector gps_lon, NumericVector target_lat, NumericVector target_lon, CharacterVector target_ids, double radius1, double radius2, bool use_haversine);
RcppExport SEXP _gps2gtfs_match_points_to_buffers_cpp(SEXP gps_latSEXP, SEXP gps_lonSEXP, SEXP target_latSEXP, SEXP target_lonSEXP, SEXP target_idsSEXP, SEXP radius1SEXP, SEXP radius2SEXP, SEXP use_haversineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gps_lat(gps_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gps_lon(gps_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_lat(target_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_lon(target_lonSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type target_ids(target_idsSEXP);
    Rcpp::traits::input_parameter< double >::type radius1(radius1SEXP);
    Rcpp::traits::input_parameter< double >::type radius2(radius2SEXP);
    Rcpp::traits::input_parameter< bool >::type use_haversine(use_haversineSEXP);
    rcpp_result_gen = Rcpp::wrap(match_points_to_buffers_cpp(gps_lat, gps_lon, target_lat, target_lon, target_ids, radius1, radius2, use_haversine));
    return rcpp_result_gen;
END_RCPP
}
// propagate_trip_ids_cpp
IntegerVector propagate_trip_ids_cpp(IntegerVector trip_ids);
RcppExport SEXP _gps2gtfs_propagate_trip_ids_cpp(SEXP trip_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type trip_ids(trip_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(propagate_trip_ids_cpp(trip_ids));
    return rcpp_result_gen;
END_RCPP
}
// assign_trip_ids_cpp
IntegerVector assign_trip_ids_cpp(CharacterVector bus_stops, CharacterVector dates, CharacterVector device_ids);
RcppExport SEXP _gps2gtfs_assign_trip_ids_cpp(SEXP bus_stopsSEXP, SEXP datesSEXP, SEXP device_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type bus_stops(bus_stopsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dates(datesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type device_ids(device_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(assign_trip_ids_cpp(bus_stops, dates, device_ids));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP wrap__assign_trip_ids_rust(SEXP, SEXP, SEXP);
RcppExport SEXP wrap__match_points_to_buffers_rust(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP wrap__propagate_trip_ids_rust(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_gps2gtfs_is_rust_compiled_cpp", (DL_FUNC) &_gps2gtfs_is_rust_compiled_cpp, 0},
    {"_gps2gtfs_haversine_distance_cpp", (DL_FUNC) &_gps2gtfs_haversine_distance_cpp, 4},
    {"_gps2gtfs_match_points_to_buffers_cpp", (DL_FUNC) &_gps2gtfs_match_points_to_buffers_cpp, 8},
    {"_gps2gtfs_propagate_trip_ids_cpp", (DL_FUNC) &_gps2gtfs_propagate_trip_ids_cpp, 1},
    {"_gps2gtfs_assign_trip_ids_cpp", (DL_FUNC) &_gps2gtfs_assign_trip_ids_cpp, 3},
    {"wrap__assign_trip_ids_rust",         (DL_FUNC) &wrap__assign_trip_ids_rust,         3},
    {"wrap__match_points_to_buffers_rust", (DL_FUNC) &wrap__match_points_to_buffers_rust, 8},
    {"wrap__propagate_trip_ids_rust",      (DL_FUNC) &wrap__propagate_trip_ids_rust,      1},
    {NULL, NULL, 0}
};

void my_init(DllInfo *dll);
RcppExport void R_init_gps2gtfs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    my_init(dll);
}
