# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib gps2gtfs, .registration = TRUE
NULL

#' Match GPS Points to Spatial Buffers in Rust
#'
#' @param gps_lat Numeric vector of GPS latitudes.
#' @param gps_lon Numeric vector of GPS longitudes.
#' @param target_lat Numeric vector of target latitudes.
#' @param target_lon Numeric vector of target longitudes.
#' @param target_ids Character vector of target IDs.
#' @param radius1 Numeric. Standard radius in meters.
#' @param radius2 Numeric. Extended radius in meters (set to 0 to ignore).
#' @param use_haversine Logical. Use Haversine distance (true) or Euclidean/Cartesian (false).
#' @noRd
match_points_to_buffers_rust <- function(gps_lat, gps_lon, target_lat, target_lon, target_ids, radius1, radius2, use_haversine) .Call(wrap__match_points_to_buffers_rust, gps_lat, gps_lon, target_lat, target_lon, target_ids, radius1, radius2, use_haversine)

#' Propagate Trip IDs in Rust
#'
#' @param trip_ids Integer vector of initial trip IDs.
#' @noRd
propagate_trip_ids_rust <- function(trip_ids) .Call(wrap__propagate_trip_ids_rust, trip_ids)

#' Assign Trip IDs in Rust
#'
#' @param bus_stops Character vector of terminal IDs.
#' @param dates Character vector of dates.
#' @param device_ids Character vector of device IDs.
#' @noRd
assign_trip_ids_rust <- function(bus_stops, dates, device_ids) .Call(wrap__assign_trip_ids_rust, bus_stops, dates, device_ids)

# nolint end
