# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_rust_compiled_cpp <- function() {
    .Call(`_gps2gtfs_is_rust_compiled_cpp`)
}

#' Haversine Distance in C++
#'
#' Calculates the great-circle distance between two points on a sphere (WGS-84).
#'
#' @param lat1 Numeric. Latitude of first point.
#' @param lon1 Numeric. Longitude of first point.
#' @param lat2 Numeric. Latitude of second point.
#' @param lon2 Numeric. Longitude of second point.
#' @return Numeric. Geodesic distance in meters.
#' @noRd
haversine_distance_cpp <- function(lat1, lon1, lat2, lon2) {
    .Call(`_gps2gtfs_haversine_distance_cpp`, lat1, lon1, lat2, lon2)
}

#' Match GPS Points to Spatial Buffers in C++
#'
#' Performs fast distance matching from GPS points to stop/terminal buffers using the Haversine formula.
#'
#' @param gps_lat NumericVector of GPS latitudes.
#' @param gps_lon NumericVector of GPS longitudes.
#' @param target_lat NumericVector of target latitudes.
#' @param target_lon NumericVector of target longitudes.
#' @param target_ids CharacterVector of target IDs.
#' @param radius1 Numeric. Standard radius in meters.
#' @param radius2 Numeric. Extended radius in meters (set to 0 to ignore).
#' @return CharacterVector of matched target IDs (NA if unmatched).
#' @noRd
match_points_to_buffers_cpp <- function(gps_lat, gps_lon, target_lat, target_lon, target_ids, radius1, radius2, use_haversine = TRUE) {
    .Call(`_gps2gtfs_match_points_to_buffers_cpp`, gps_lat, gps_lon, target_lat, target_lon, target_ids, radius1, radius2, use_haversine)
}

#' Propagate Trip IDs
#'
#' Propagates trip IDs forward from the terminal exit point to the terminal entry point.
#'
#' @param trip_ids IntegerVector of initial trip IDs (with 0s for intermediate points).
#' @return IntegerVector of propagated trip IDs.
#' @noRd
propagate_trip_ids_cpp <- function(trip_ids) {
    .Call(`_gps2gtfs_propagate_trip_ids_cpp`, trip_ids)
}

#' Assign Trip IDs
#'
#' Pairs consecutive terminal exits and entries for the same device, date, and different terminals.
#'
#' @param bus_stops CharacterVector of terminal IDs.
#' @param dates CharacterVector of dates (as strings).
#' @param device_ids CharacterVector of device IDs.
#' @return IntegerVector of assigned trip IDs (with 0 for unmatched).
#' @noRd
assign_trip_ids_cpp <- function(bus_stops, dates, device_ids) {
    .Call(`_gps2gtfs_assign_trip_ids_cpp`, bus_stops, dates, device_ids)
}

